--Password: CD-r5fdbsvr1#
delete from SAT_LOCKING where CUSER_ID='hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '11', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '12', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '20', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '30', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '40', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '50', 'hmc'

SELECT * FROM GSM_JRNGRP_GOA_DEPT

SELECT * FROM GSM_JRNGRP_GOA --
select * from GSM_JRNGRP_GOA_DEPT --A		--CompanyID = RCD, CGOA_CODE = AP, CGLACCOUNT_NO = 12.50.0000, CDEPT_CODE + ACC
SELECT * FROM GSM_GOA --B					--CompanyID = RCD,  CGOA_CODE = AP
SELECT * FROM GSM_GOA_COA  --C				--CompanyID = RCD, CGOA_CODE = AP, CGLACCOUNT_NO = 12.50.0000
select * from GSM_DEPARTMENT --D			-- CDEPT_CODE = ACC
select * from GSM_COA --E					-- CGLACCOUNT_NO = 12.50.0000

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '10' , 'A', 'hmc'

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '11','A','ARDEP','1','12.50.0000','HMC')

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '11','A','ARDEP','1','12.50.0000','HMC')
--LIST GOA DEPT
INSERT into GSM_GOA_COA (CCOMPANY_ID,CGOA_CODE,CGLACCOUNT_NO)
VALUES ('RCD', 'AP', '12.50.0000')

--Tab Account Setting (GRUP GOA LIST) 
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '10' , 'A', 'hmc';

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'AP', 'hmc'

--RSF, RSF2

--TAB ACCOUNT SETTING GOA DEPT LIST
INSERT INTO GSM_JRNGRP_GOA_DEPT (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, CDEPT_CODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '11','A','AP','RSF','12.50.0000','HMC')
--EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST @CCOMPANY_ID, @CPROPERTY_ID, '10' , @CJOURNAL_GRP_CODE, @CGOA_CODE, @CUSER_LOGIN_ID
SELECT * FROM GSM_JRNGRP_GOA_DEPT

--Query yang menghasilkan value untuk SP DEPT LIST
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'rcd', 'jbmpc', '10', 'A', 'AP', 'HMC'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'Z' , 'ARDEP', 'hmc'

---GOA DEPT Detail ===> for one record
		---RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT @CCOMPANY_ID	, @CPROPERTY_ID	, @CJOURNAL_GROUP_TYPE	, @CJOURNAL_GROUP_CODE	, @CGOA_CODE	, @CDEPT_CODE	, @CUSER_LOGIN_ID
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'Z' , 'ARDEP','ACC', 'hmc'


EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '11', 'A' , 'ARDEP','ACC', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'Z' , 'ARDEP','ACC', 'hmc'


--GetLIST dan --Maintain
---RSP_GS_GET_JOURNAL_GRP_GOA_DETAIL @CCOMPANY_ID,  @CPROPERTY_ID, @CJOURNAL_GROUP_TYPE,  @CJOURNAL_GROUP_CODE, @CGOA_CODE , @CUSER_LOGIN_ID
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '10' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '11' , 'A', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DETAIL 'RCD', 'jbmpc', '10' , 'A', 'AP', 'HMC'


EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD','JBMPC', '10', 'A','ARDEP', '1','12.50.0000','EDIT', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD','JBMPC', '10', 'A','AP', '1','12.50.0000','EDIT', 'hmc'

---DELETED 
----EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT "Company Id" "Property Id"	'10'	"Journal Group" 
--"Department Code" "Group of Account" 'DELETE' Login User Id

--GetLIST dan --Maintain
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'Z' , 'ARDEP','RSF', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '10', 'Z', 'ARDEP','ACC','12.50.0000' ,'DELETE', 'hmc'


-----TAB UTILTY
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '11', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '10' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '11' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DETAIL 'RCD', 'jbmpc', '11' , 'A', 'AP', 'HMC'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '11', 'A' , 'AP','RSF', 'hmc'

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '10','A','ARDEP','1','12.50.0000','HMC')

--insert to GOA DEPT
INSERT INTO GSM_JRNGRP_GOA_DEPT (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, CDEPT_CODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '10','A','AP','RSF','12.50.0000','HMC')

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '50','A','ARDEP','1','12.50.0000','HMC')

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '12', 'A' , 'ARDEP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '12', 'A' , 'AP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '40', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'

EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '11', 'A', 'ARDEP','HRD','12.50.0000' ,'DELETE', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '40', 'A', 'ARDEP','RSF','12.50.0000' ,'ADD', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '40', 'A', 'ARDEP','ACC','12.50.0000' ,'ADD', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '40', 'A', 'AP','RSF','12.50.0000' ,'ADD', 'hmc'
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '11', 'A','ARDEP', '1', '12.50.0000','EDIT', 'hmc'


--INPUT MANUAL
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '10', 'A','ARDEP', '0', '12.50.0000','EDIT', 'hmc'
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '10', 'A','AP', '1', '12.50.0000','EDIT', 'hmc'
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '11', 'A','AP', '1', '12.50.0000','EDIT', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '10', 'A', 'ARDEP','ACC','12.50.0000' ,'EDIT', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '10', 'A', 'AP','RSF','12.50.0000' ,'EDIT', 'hmc'


EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST @CCOMPANY_ID, @CPROPERTY_ID, '10' , @CJOURNAL_GRP_CODE, @CUSER_LOGIN_ID


EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '10' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '50' , 'A', 'hmc'


--[CR]
SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'RCD', '_BS_JOURNAL_GRP_TYPE', '', 'EN')
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '30', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '10' , 'A', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'AP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '11' , 'A', 'hmc';

EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 
 'RCD'
, 'jbmpc'
, '11' 
, 'A'
, 'AP'
, 0
, '12.50.0000'
, 'EDIT'
, 'HMC'

CGLACCOUNT_NO

EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','ARDEP'
EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','AP'
EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','ACCR'
EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','AD'

select * from GSM_GOA
RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT


EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','AP'

RSP_GS_GET_PROPERTY_LIST 'rcd', 'hmc'


SELECT * FROM GSM_JRNGRP (NOLOCK) WHERE CCOMPANY_ID = 'RCD' AND CPROPERTY_ID = 'JBMPC'AND CJRNGRP_TYPE = '10'
CJRNGRP_TYPE

RSP_GS_UPLOAD_JOURNAL_GROUP 'rcd','jbmpc','hmc', '',''
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'

exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'hmc'

exec RSP_GS_GET_UNIT_TYPE_LIST 'rcd','jbmpc', 'hmc'

exec RSP_GS_VALIDATE_UPLOAD_JOURNAL_GROUP ''

SELECT * FROM GSM_JRNGRP (NOLOCK) WHERE CCOMPANY_ID ='RCD' AND CPROPERTY_ID = 'ashmd'
                    AND CJRNGRP_TYPE ='10' 


begin transaction
CREATE TABLE #UNIT_PROMOTION_TYPE(NO		INT
				, UnitPromotionTypeCode	VARCHAR(20)
				, UnitPromotionTypeName	NVARCHAR(100)
				, GrossAreaSize		NUMERIC(5,2)
				, NetAreaSize		NUMERIC(5,2)
				, CommonArea		NUMERIC(5,2)
				, Active			BIT
				, NonActiveDate		VARCHAR(8)
				)

INSERT INTO #UNIT_PROMOTION_TYPE (NO, UnitPromotionTypeCode, UnitPromotionTypeName, GrossAreaSize, NetAreaSize, CommonArea, Active, NonActiveDate)
VALUES
    (1, 'PROMO1', 'Promotion Type 1', 150, 120, 10, 1, '20210101'),
    (2, 'ADVERS', 'Promotion Type 2', 200, 180, 20, 0, '20111212'),
    (3, 'PROMO1', 'Promotion Type 3', 100, 85, 30, 1, '20230715'),
    (4, 'PROMO4', 'Promotion Type 4', 180, 160, 40, 0, '20230202'),
    (5, 'PROMO5', 'Promotion Type 5', 120, 95, 50, 1, '20230202');


EXEC RSP_GS_VALIDATE_UPLOAD_UNIT_PROMOTION_TYPE 'rcd', 'JBMPC', 'ERC', 'njesfnf243bkjkdfs4u4b5', 1

SELECT CCOMPANY_ID FROM GST_XML_RESULT WHERE CCOMPANY_ID = 'RCD' AND CUSER_ID = 'ERC' AND CKEY_GUID = 'njesfnf243bkjkdfs4u4b5'

EXECUTE RSP_ConvertXMLToTable 'RCD', 'ERC', 'njesfnf243bkjkdfs4u4b5'

rollback 


--LIST TAB SUPPLIER
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '50', 'hmc'

--TRANSACTION
begin transaction
 CREATE TABLE #JRNLGROUP  (No INT, 
                              JournalGroup VARCHAR(8), 
                              JournalGroupName VARCHAR(80), 
                              EnableAccrual BIT,
                              ValidFlag BIT );

INSERT INTO #JRNLGROUP (NO, JournalGroup, JournalGroupName, EnableAccrual, ValidFlag)
VALUES
    (1, 'BGDF356', 'Dummy1', 0, 0),
    (2, 'BGDF357', 'Dummy 2', 1, 0);

exec RSP_GS_VALIDATE_UPLOAD_JOURNAL_GROUP 'RCD', 'ASHMD','hmc', '143b60c44c5843ce952a66887f02a500',0, '10'

SELECT CCOMPANY_ID FROM GST_XML_RESULT WHERE CCOMPANY_ID = 'RCD' AND CUSER_ID = 'hmc' AND CKEY_GUID = '143b60c44c5843ce952a66887f02a500'

EXEC RSP_ConvertXMLToTable 'RCD', 'hmc', '143b60c44c5843ce952a66887f02a500';

rollback




exec RSP_GS_UPLOAD_JOURNAL_GROUP 'rcd','jbmpc', 'hmc', '34dfc53210bf47ae84c360e81bb37a2d',1,'10'


EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'ASHMD', '10', 'hmc'

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_GS_MAINTAIN_JOURNAL_GROUP]
		@CCOMPANY_ID = N'RCD',
		@CPROPERTY_ID = N'ASHMD',
		@CJRNGRP_TYPE = N'10',
		@CJRNGRP_CODE = N'AAA12',
		@CJRNGRP_NAME = N'The Panturas',
		@LACCRUAL = 0,
		@CACTION = N'DELETE',
		@CUSER_ID = N'hmc'
SELECT	'Return Value' = @return_value
GO
---EDIT GOA DEPT



--exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT

--Query LookUP GOACOA
EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','ARDEP'
--Query LookUP DEPT
exec RSP_GS_GET_DEPT_LOOKUP_LIST 'RCD','hmc'

--LIST GOA DEPT
exec RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD', 'JBMPC', '10', 'A','ARDEP','hmc'

--EDIT GOA DEPT
USE [BIMASAKTI_11]
GO
DECLARE	@return_value int

EXEC	@return_value = [dbo].[RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT]
		@CCOMPANY_ID = N'rcd',
		@CPROPERTY_ID = N'jbpmc',
		@CJRNGRP_TYPE = N'11',
		@CJRNGRP_CODE = N'A',
		@CGOA_CODE = N'ARDEP',
		@CDEPT_CODE = N'ACC',
		@CGLACCOUNT_NO = N'12.30.0000',
		@CACTION = N'EDIT',
		@CUSER_ID = N'hmc'

SELECT	'Return Value' = @return_value
GO

exec RSP_GL_GENERATE_ACCOUNT_BUDGET

select * from GST_UPLOAD_PROCESS_STATUS