--Password: CD-r5fdbsvr1#
delete from SAT_LOCKING where CUSER_ID='aoc'

delete from SAT_LOCKING where CUSER_ID='hmc'

EXEC RSP_LM_GET_UNIT_TYPE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_CATEGORY_ID , @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_BILLING_RULE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_ID, @LACTIVE_ONLY, @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'ASHMD','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'JBMPC','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'LMPNG','','hmc'


EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'RCD', 'JBMPC','1BRoom', 0, 'hmc'

--RSP_GS_GET_UNIT_TYPE_BILLING_RULE_DT 
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_ID, @CBIILING_RULE_CODE, @CUSER_LOGIN_ID

EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'Rules001', 'hmc'



exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'admin'

SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'Login Company Id', '_PERIOD_MODE', '', 'EN')
SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'RCD', '_PERIOD_MODE', '', 'EN')


EXEC RSP_GS_GET_SALES_TAX_LIST 'RCD', 'hmc' 




EXEC RSP_LM_GET_CHARGES_TYPE_LIST 'hmc', 'ASHMD', '','admin'
exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'admin'
LINSTALLMENT
0
CDP_CHARGE_ID	CDP_CHARGE_NAME CINSTALLMENT_CHARGE_ID

CINSTALLMENT_CHARGE_ID	CINSTALLMENT_CHARGE_NAME
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'RULes03', 'hmc'

EXEC RSP_LM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE 
Login Company Id
, "Selected Property Id"
, "Unit Type Id"
, "Billing Rule" Code
, Flag Active [True] / [False]
, Login User Id

EXEC RSP_LM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE 'rcd','JBMPC','1BRoom', 'RULES03', 1, 'hmc'
EXEC RSP_LM_GET_CHARGES_TYPE_LIST 'RCD', 'JBMPC', '07', 'hmc'

EXEC RSP_LM_GET_UNIT_TYPE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'ASHMD','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'JBMPC','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'LMPNG','','hmc'

exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '07','hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '','hmc'
--RSP_LM_GET_CHARGES_TYPE_LIST

SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'rcd', '_PERIOD_MODE', '', 'en')

exec RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'rcd','ashmd', '1BRoom', '0','hmc'

exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Ashmd', '', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Lmpng', '', 'hmc'

exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'jbmpc', '07', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Ashmd', '07', 'hmc'
exec RSP_LM_GET_CHARGES_TYPE_LIST 'rcd', 'Lmpng', '07', 'hmc'

exec RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'rcd','JBMPC', '1BRoom', '1','hmc'
exec RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'rcd','JBMPC', '1BRoom', '0','hmc'


EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'RULES001', 'hmc'

USE [BIMASAKTI_11]
GO
DECLARE	@return_value int
EXEC	@return_value = [dbo].[RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULE]
		@CCOMPANY_ID = N'RCD',
		@CPROPERTY_ID = N'JBMPC',
		@CUNIT_TYPE_ID = N'1BRoom',
		@CBILLING_RULE_CODE = N'RULES001',
		@CBILLING_RULE_NAME = N'Iuran Pengembangan',
		@LBOOKING_FEE = 1,
		@CBOOKING_FEE_CHARGES_ID = N'G002',
		@LWITH_DP = 1,
		@IDP_PERCENTAGE = 22,
		@IDP_INTERVAL = 22,
		@CDP_PERIOD_MODE = N'03',
		@CDP_CHARGE_ID = N'DP',
		@LINSTALLMENT = 1,
		@IINSTALLMENT_PERCENTAGE = 1,
		@IINSTALLMENT_INTERVAL = 12,
		@CINSTALLMENT_PERIOD_MODE = N'03',
		@CINSTALLMENT_CHARGE_ID = N'GLK01',
		@LBANK_CREDIT = 0,
		@IBANK_CREDIT_PERCENTAGE = 0,
		@IBANK_CREDIT_INTERVAL = 0,
		@LACTIVE = 1,
		@CACTION = N'EDIT',
		@CUSER_ID = N'HMC'

SELECT	'Return Value' = @return_value
GO

RSP_GS_VALIDATE_UPLOAD_JOURNAL_GROUP
