EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '11', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '12', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '20', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '30', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '40', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '50', 'hmc'

SELECT * FROM GSM_JRNGRP_GOA_DEPT

SELECT * FROM GSM_JRNGRP_GOA --
select * from GSM_JRNGRP_GOA_DEPT --A		--CompanyID = RCD, CGOA_CODE = AP
SELECT * FROM GSM_GOA --B					--CompanyID = RCD,  CGOA_CODE = AP
SELECT * FROM GSM_GOA_COA  --C				--CompanyID = RCD,
select * from GSM_DEPARTMENT --D
select * from GSM_COA --E

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '10' , 'A', 'hmc'

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '10','Z','AP','1','12.10.0000','HMC')

--LIST GOA DEPT

INSERT INTO GSM_JRNGRP_GOA_DEPT (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, CDEPT_CODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '10','Z','ARDEP','ACC','12.50.0000','HMC')

INSERT into GSM_GOA_COA (CCOMPANY_ID,CGOA_CODE,CGLACCOUNT_NO)
VALUES ('RCD', 'AP', '12.50.0000')

--Tab Account Setting (GRUP GOA LIST) 
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '10' , 'A', 'hmc';

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'ACC' , 'AP', 'hmc'



--TAB ACCOUNT SETTING GOA DEPT LIST

--EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST @CCOMPANY_ID, @CPROPERTY_ID, '10' , @CJOURNAL_GRP_CODE, @CGOA_CODE, @CUSER_LOGIN_ID
SELECT * FROM GSM_JRNGRP_GOA_DEPT

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'rcd', 'jbmpc', '10', 'A', 'AP', 'HMC'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'Z' , 'ARDEP', 'hmc'

---GOA DEPT Detail ===> for one record
		---RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT @CCOMPANY_ID	, @CPROPERTY_ID	, @CJOURNAL_GROUP_TYPE	, @CJOURNAL_GROUP_CODE	, @CGOA_CODE	, @CDEPT_CODE	, @CUSER_LOGIN_ID
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'A' , 'ARDEP','1', 'hmc'