delete from SAT_LOCKING where CUSER_ID='hmc'

EXEC RSP_LM_GET_UNIT_TYPE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_CATEGORY_ID , @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_BILLING_RULE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_ID, @LACTIVE_ONLY, @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'ASHMD','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'JBMPC','','hmc'

--ada error pada SP ini
EXEC RSP_GS_GET_UNIT_TYPE_BILLING_RULE_LIST 'RCD', 'JBMPC','2BRoom', '', 'hmc'

EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','2BRoom', 'RULES01', 'hmc'

EXEC RSP_LM_MAINTAIN_UNIT_TYPE_BILLING_RULE 'RCD', 'JBMPC', '2BRoom', 'RULES01', 'aa', 0,2,2,'abc',1,2,12,'abc'

exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'admin'