EXEC RSP_GS_GET_SALES_TAX_PCT_LIST
delete from SAT_LOCKING where CUSER_ID='hpc'
SELECT CBASE_CURRENCY_CODE 
      ,CLOCAL_CURRENCY_CODE
FROM GSM_COMPANY (NOLOCK)
WHERE CCOMPANY_ID = 'Rcd'

SELECT LINCREMENT_FLAG
      ,LAPPROVAL_FLAG 
FROM GSM_TRANSACTION_CODE (NOLOCK)
WHERE CCOMPANY_ID = 'rcd'
AND CTRANSACTION_CODE='000030'

exec RFN_GET_DB_TODAY 'Rcd'

RSP_GL_GET_SYSTEM_PARAM 'Rcd'

SELECT IMIN_YEAR=CAST(MIN(CYEAR) AS INT),IMAX_YEAR=CAST(MAX(CYEAR) AS INT) FROM GSM_PERIOD (NOLOCK)WHERE CCOMPANY_ID = 'RCD'
--getLIST
exec RSP_GL_SEARCH_ACTIVE_REVERSING_LIST 'rcd', 'admin', '202306', '', 'EN'

RSP_GL_GET_JOURNAL_DETAIL_LIST '00', 'EN'


select * from GSM_PERIOD_DT

exec dbo.RFN_GET_DB_TODAY 'RCD'

exec RSP_GL_GET_JOURNAL_DETAIL_LIST '',''