--Password: CD-r5fdbsvr1#
delete from SAT_LOCKING where CUSER_ID='aoc'

delete from SAT_LOCKING where CUSER_ID='hmc'

EXEC RSP_LM_GET_UNIT_TYPE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_CATEGORY_ID , @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_BILLING_RULE_LIST @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_ID, @LACTIVE_ONLY, @CUSER_LOGIN_ID

EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'ASHMD','','hmc'
EXEC RSP_GS_GET_UNIT_TYPE_LIST 'RCD', 'JBMPC','','hmc'


EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_LIST 'RCD', 'JBMPC','1BRoom', 0, 'hmc'

--RSP_GS_GET_UNIT_TYPE_BILLING_RULE_DT 
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT @CLOGIN_COMPANY_ID, @Selected_Property_ID, @CUNIT_TYPE_ID, @CBIILING_RULE_CODE, @CUSER_LOGIN_ID

EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'Rule Hapus', 'hmc'



exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'admin'

SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'Login Company Id', '_PERIOD_MODE', '', 'EN')
SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'RCD', '_PERIOD_MODE', '', 'EN')


EXEC RSP_GS_GET_SALES_TAX_LIST 'RCD', 'hmc' 




EXEC RSP_LM_GET_CHARGES_TYPE_LIST 'hmc', 'ASHMD', '','admin'
exec RSP_GS_GET_PROPERTY_LIST 'rcd', 'admin'
LINSTALLMENT
0
CDP_CHARGE_ID	CDP_CHARGE_NAME CINSTALLMENT_CHARGE_ID

CINSTALLMENT_CHARGE_ID	CINSTALLMENT_CHARGE_NAME
EXEC RSP_LM_GET_UNIT_TYPE_BILLING_RULE_DT 'RCD', 'JBMPC','1BRoom', 'RULes03', 'hmc'

EXEC RSP_LM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE 
Login Company Id
, "Selected Property Id"
, "Unit Type Id"
, "Billing Rule" Code
, Flag Active [True] / [False]
, Login User Id

EXEC RSP_LM_ACTIVE_INACTIVE_UNIT_TYPE_BILLING_RULE 'rcd','JBMPC','1BRoom', 'RULES03', 1, 'hmc'
EXEC RSP_LM_GET_CHARGES_TYPE_LIST 'RCD', 'JBMPC', '07', 'hmc'