--Password: CD-r5fdbsvr1#
delete from SAT_LOCKING where CUSER_ID='aoc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '11', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '12', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '20', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '30', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '40', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '50', 'hmc'

SELECT * FROM GSM_JRNGRP_GOA_DEPT

SELECT * FROM GSM_JRNGRP_GOA --
select * from GSM_JRNGRP_GOA_DEPT --A		--CompanyID = RCD, CGOA_CODE = AP, CGLACCOUNT_NO = 12.50.0000, CDEPT_CODE + ACC
SELECT * FROM GSM_GOA --B					--CompanyID = RCD,  CGOA_CODE = AP
SELECT * FROM GSM_GOA_COA  --C				--CompanyID = RCD, CGOA_CODE = AP, CGLACCOUNT_NO = 12.50.0000
select * from GSM_DEPARTMENT --D			-- CDEPT_CODE = ACC
select * from GSM_COA --E					-- CGLACCOUNT_NO = 12.50.0000

EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '10' , 'A', 'hmc'

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '11','A','ARDEP','1','12.50.0000','HMC')

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '11','A','ARDEP','1','12.50.0000','HMC')
--LIST GOA DEPT
INSERT into GSM_GOA_COA (CCOMPANY_ID,CGOA_CODE,CGLACCOUNT_NO)
VALUES ('RCD', 'AP', '12.50.0000')

--Tab Account Setting (GRUP GOA LIST) 
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '10' , 'A', 'hmc';

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'AP', 'hmc'

--RSF, RSF2

--TAB ACCOUNT SETTING GOA DEPT LIST
INSERT INTO GSM_JRNGRP_GOA_DEPT (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, CDEPT_CODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '11','A','AP','RSF','12.50.0000','HMC')
--EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST @CCOMPANY_ID, @CPROPERTY_ID, '10' , @CJOURNAL_GRP_CODE, @CGOA_CODE, @CUSER_LOGIN_ID
SELECT * FROM GSM_JRNGRP_GOA_DEPT

--Query yang menghasilkan value untuk SP DEPT LIST
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'rcd', 'jbmpc', '10', 'A', 'AP', 'HMC'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'Z' , 'ARDEP', 'hmc'

---GOA DEPT Detail ===> for one record
		---RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT @CCOMPANY_ID	, @CPROPERTY_ID	, @CJOURNAL_GROUP_TYPE	, @CJOURNAL_GROUP_CODE	, @CGOA_CODE	, @CDEPT_CODE	, @CUSER_LOGIN_ID
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'Z' , 'ARDEP','ACC', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'Z' , 'ARDEP','RSF', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'Z' , 'ARDEP','ACC', 'hmc'


--GetLIST dan --Maintain
---RSP_GS_GET_JOURNAL_GRP_GOA_DETAIL @CCOMPANY_ID,  @CPROPERTY_ID, @CJOURNAL_GROUP_TYPE,  @CJOURNAL_GROUP_CODE, @CGOA_CODE , @CUSER_LOGIN_ID
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '10' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '11' , 'A', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DETAIL 'RCD', 'jbmpc', '10' , 'A', 'AP', 'HMC'


EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD','JBMPC', '10', 'A','ARDEP', '1','12.50.0000','EDIT', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD','JBMPC', '10', 'A','AP', '1','12.50.0000','EDIT', 'hmc'

---DELETED 
----EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT "Company Id" "Property Id"	'10'	"Journal Group" 
--"Department Code" "Group of Account" 'DELETE' Login User Id

--GetLIST dan --Maintain
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '10', 'Z' , 'ARDEP','RSF', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '10', 'Z', 'ARDEP','ACC','12.50.0000' ,'DELETE', 'hmc'


-----TAB UTILTY
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '10', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '11', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '10' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '11' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DETAIL 'RCD', 'jbmpc', '11' , 'A', 'AP', 'HMC'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_DT 'RCD','JBMPC', '11', 'A' , 'AP','RSF', 'hmc'

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '10','A','ARDEP','1','12.50.0000','HMC')

--insert to GOA DEPT
INSERT INTO GSM_JRNGRP_GOA_DEPT (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, CDEPT_CODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '10','A','AP','RSF','12.50.0000','HMC')

INSERT INTO GSM_JRNGRP_GOA (CCOMPANY_ID, CPROPERTY_ID, CJRNGRP_TYPE, CJRNGRP_CODE, CGOA_CODE, LDEPARTMENT_MODE, CGLACCOUNT_NO, CCREATE_BY)
VALUES						('RCD', 'JBMPC', '50','A','ARDEP','1','12.50.0000','HMC')

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '12', 'A' , 'ARDEP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '12', 'A' , 'AP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '40', 'A' , 'ARDEP', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'

EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '11', 'A', 'ARDEP','HRD','12.50.0000' ,'DELETE', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '40', 'A', 'ARDEP','RSF','12.50.0000' ,'ADD', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '40', 'A', 'ARDEP','ACC','12.50.0000' ,'ADD', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '40', 'A', 'AP','RSF','12.50.0000' ,'ADD', 'hmc'
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '11', 'A','ARDEP', '1', '12.50.0000','EDIT', 'hmc'


--INPUT MANUAL
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '10', 'A','ARDEP', '0', '12.50.0000','EDIT', 'hmc'
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '10', 'A','AP', '1', '12.50.0000','EDIT', 'hmc'
Exec RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 'RCD', 'JBMPC', '11', 'A','AP', '1', '12.50.0000','EDIT', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '10', 'A', 'ARDEP','ACC','12.50.0000' ,'EDIT', 'hmc'
EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT_DEPT  'RCD','JBMPC', '10', 'A', 'AP','RSF','12.50.0000' ,'EDIT', 'hmc'


EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST @CCOMPANY_ID, @CPROPERTY_ID, '10' , @CJOURNAL_GRP_CODE, @CUSER_LOGIN_ID


EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '10' , 'A', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '10', 'A' , 'AP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '50' , 'A', 'hmc'


--[CR]
SELECT * FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'RCD', '_BS_JOURNAL_GRP_TYPE', '', 'EN')
EXEC RSP_GS_GET_JOURNAL_GRP_LIST 'RCD', 'JBMPC', '30', 'hmc'
EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST 'RCD', 'jbmpc', '10' , 'A', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_DEPT_LIST 'RCD','JBMPC', '11', 'A' , 'AP', 'hmc'

EXEC RSP_GS_GET_JOURNAL_GRP_GOA_LIST  'RCD', 'jbmpc', '11' , 'A', 'hmc';

EXEC RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT 
 'RCD'
, 'jbmpc'
, '11' 
, 'A'
, 'AP'
, 0
, '12.50.0000'
, 'EDIT'
, 'HMC'

CGLACCOUNT_NO

EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','ARDEP'

RSP_GS_MAINTAIN_JOURNAL_GROUP_ACCOUNT


EXEC RSP_GS_GET_GOA_COA_LIST 'RCD','AP'